version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    target-branch: "1.x"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    open-pull-requests-limit: 10
    groups:
      patch-and-minor:
        update-types:
          - patch
          - minor

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "1.x"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    groups:
      actions:
        patterns:
          - "*"
